### ISSUE TITLE
Release 2.11

### ISSUE THREAD

**Issue by Krinkle** [qunitjs/qunit#1463]
Some noteworthy changes that have landed since 2.10:

* Core: Decide "No tests" based on test count, not assert count (fixes https://github.com/qunitjs/qunit/issues/1405).
* Assert: Implement `assert.true()` and `assert.false()` (pull https://github.com/qunitjs/qunit/pull/1445).
* HTML Reporter: Add fuzzy search feature to module dropdown filter (pull https://github.com/qunitjs/qunit/issues/1438 by @ventuno).
* All: Official support for Node 12 and Node 14 (pull https://github.com/qunitjs/qunit/pull/1448).
* Docs: Launched new [qunitjs.com](https://qunitjs.com/) and [api.qunitjs.com](https://api.qunitjs.com/assert/async/). Mobile-friendly and with multisite search. (ref https://github.com/qunitjs/qunitjs.com/issues/151, https://github.com/qunitjs/qunit/issues/1460, https://github.com/qunitjs/qunit/issues/1458#issuecomment-661576550).
* CLI: Improve file finder performance for non-glob argument. (ref https://github.com/qunitjs/qunit/pull/1385)

Some things to perhaps still do before new release:

* [x] Drop support for Node 6 and Node 8 (EOL). Remove dependency on `resolve` package and its indirect dependency on `path-parse` (review pull https://github.com/qunitjs/qunit/pull/1464).
* [x] Docs: Add "version added" annotation to the API site (review pull https://github.com/qunitjs/qunit/pull/1462).
* [x] Docs: In light of `assert.true`, decide what to do with `assert.ok` and update docs accordingly to reflect current best practice (see https://github.com/qunitjs/qunit/issues/1450).

/cc @trentmwillis, @leobalter, @JamesMGreene

**Comment by Krinkle** [comment]
I'm working through the release process this week. I'm taking it slow because I'm doing this in lock-step with documenting the new release process (solving https://github.com/qunitjs/qunit/issues/1350), specifically in a way that allows all Node-execution to happen in an isolated container (no git hooks, no push credentials), and fully supports 2FA-enabled mode of npm, and doesn't require branch protection to be bypassed.

**Comment by Krinkle** [comment]
@ventuno I'd like to mention you in the [@qunitjs](https://twitter.com/qunitjs) tweet about this release. Let me know if that's okay.

If yes, how should I refer to you? (GH nick, name, or Twitter handle).

**Comment by ventuno** [comment]
Thanks @Krinkle, you can use my GH nickname if you want, I don't have a Twitter handle :-).
