### ISSUE TITLE
Build improvements

### ISSUE THREAD

**Issue by jzaefferer** [qunitjs/qunit#582]
A few things I noticed recently that we should fix or improve in our build.
- [x] Use jscs with jQuery preset (and [additional settings](https://github.com/jzaefferer/jquery-validation/blob/master/.jscsrc) if still necessary)
- [x] Simplify jshint configuration to use a single source set, speed up execution
- [x] Make watch task run the default task immediately before starting to watch for changes (I have no clue why that isn't the default)
- [x] Update test-on-node task to remove the globals except for `QUnit`
